from sqlalchemy import (
    Column, Integer, String, Date, Numeric, Text, Boolean, TIMESTAMP, 
    ForeignKey, CheckConstraint, UniqueConstraint, JSON
)
from sqlalchemy.sql import func
from sqlalchemy.orm import relationship
from core.database import Base

class User(Base):
    __tablename__ = "users"
    id = Column(Integer, primary_key=True, index=True)
    username = Column(String(50), unique=True, nullable=False, index=True)
    password_hash = Column(String(255), nullable=False)
    role = Column(String(20), default="user")
    pic_recruiter = Column(String(100))
    display_name = Column(String(100))
    created_at = Column(TIMESTAMP, server_default=func.now())
    last_login = Column(TIMESTAMP)

class UploadCycle(Base):
    __tablename__ = "upload_cycles"
    id = Column(Integer, primary_key=True, index=True)
    cycle_name = Column(String(100), nullable=False)
    created_by = Column(Integer, ForeignKey("users.id"))
    created_at = Column(TIMESTAMP, server_default=func.now())
    started_at = Column(TIMESTAMP, server_default=func.now())
    ended_at = Column(TIMESTAMP)

class UploadStatus(Base):
    __tablename__ = "upload_status"
    id = Column(Integer, primary_key=True, index=True)
    cycle_id = Column(Integer, ForeignKey("upload_cycles.id", ondelete="CASCADE"))
    user_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"))
    status = Column(String(20), default="Belum Mulai")
    first_compile_at = Column(TIMESTAMP)
    done_at = Column(TIMESTAMP)
    __table_args__ = (UniqueConstraint('cycle_id', 'user_id'),)

class UploadLog(Base):
    __tablename__ = "upload_logs"
    id = Column(Integer, primary_key=True, index=True)
    cycle_id = Column(Integer, ForeignKey("upload_cycles.id"))
    user_id = Column(Integer, ForeignKey("users.id"))
    file_name = Column(String(255))
    file_size_bytes = Column(Integer)
    file_hash = Column(String(64))
    status = Column(String(20))
    record_count = Column(Integer)
    error_details = Column(Text)
    uploaded_at = Column(TIMESTAMP, server_default=func.now())

class FPTK(Base):
    __tablename__ = "fptk"
    id = Column(Integer, primary_key=True, index=True)
    kode_unik = Column(String(50), nullable=False, index=True)
    posisi = Column(String(255), nullable=False, index=True)
    kode_pic = Column(String(50))
    fptk_date_real = Column(Date)
    fptk_date_kode = Column(Date)
    kode_angka = Column(String(50))
    business_unit = Column(String(100), index=True)
    direktorat = Column(String(100), index=True)
    divisi = Column(String(100))
    department = Column(String(100))
    level_fptk = Column(String(50))
    level_number = Column(Integer)
    alasan_permintaan_fptk = Column(Text)
    category_fptk = Column(String(100))
    pic_recruiter = Column(String(100), index=True)
    filter_kategorisasi_fptk = Column(String(50), index=True)
    vacancy = Column(Integer)
    status = Column(String(20), CheckConstraint("status IN ('OP', 'Closed', 'Cancel')"))
    week_fptk_date = Column(Integer)
    month_fptk_date = Column(String(20))
    fptk_cancel_date = Column(Date)
    week_cancel_date = Column(Integer)
    month_cancel_date = Column(String(20))
    offering_date = Column(Date)
    week_offering_date = Column(Integer)
    month_offering = Column(String(20))
    jumlah_sla = Column(Integer)
    deadline_sla = Column(Date)
    detail_sla = Column(Text)
    keterangan_lulus_sla = Column(Text)
    keterangan_tidak_lulus_sla = Column(Text)
    keterangan_cancel = Column(Text)
    nama_kandidat = Column(String(255))
    estimasi_join = Column(Date)
    kebutuhan_laptop = Column(String(10))
    lokasi_onboarding = Column(String(100))
    tanggal_upload_web = Column(Date)
    user_manager = Column(String(100))
    indirect_user = Column(String(100))
    lokasi_kerja = Column(String(100))
    lokasi_hr = Column(String(100))
    status_karyawan = Column(String(50))
    kode_bu = Column(String(20), index=True)
    fptk_availability = Column(String(1), CheckConstraint("fptk_availability IN ('Y', 'N')"))
    remark = Column(Text)
    created_at = Column(TIMESTAMP, server_default=func.now())
    last_updated_at = Column(TIMESTAMP)
    last_compile_action = Column(String(20))
    source_file = Column(String(255))
    source_file_hash = Column(String(64))
    source_user_id = Column(Integer, ForeignKey("users.id"))
    source_cycle_id = Column(Integer, ForeignKey("upload_cycles.id"))
    is_sto = Column(Boolean, default=False)
    
    __table_args__ = (UniqueConstraint('kode_unik', 'posisi'),)

class DBKodePosisi(Base):
    __tablename__ = "db_kode_posisi"
    id = Column(Integer, primary_key=True, index=True)
    kode = Column(String(50))
    position = Column(String(255), nullable=False, index=True)
    location = Column(String(100))
    business_unit = Column(String(100), index=True)
    division_chris = Column(String(100))
    department_chris = Column(String(100))
    user_manager = Column(String(100))
    indirect_user = Column(String(100))
    directorate = Column(String(100))
    year = Column(Integer)
    __table_args__ = (UniqueConstraint('position', 'location', 'business_unit'),)

class DBSourcing(Base):
    __tablename__ = "db_sourcing"
    id = Column(Integer, primary_key=True, index=True)
    no = Column(Integer)
    sourcing_date = Column(Date, nullable=False, index=True)
    kode_unik = Column(String(50), nullable=False, index=True)
    posisi = Column(String(255))
    model_rekrutmen = Column(String(50))
    rekruter = Column(String(100))
    sumber_sourcing = Column(String(100))
    nama = Column(String(255), nullable=False, index=True)
    nama_universitas_top10 = Column(String(255))
    nama_universitas_lainnya = Column(String(255))
    jenjang_pendidikan = Column(String(50))
    jurusan = Column(String(100))
    tahun_lulus = Column(Integer)
    ipk = Column(Numeric(3,2))
    skor_bahasa_inggris = Column(String(50))
    university_tier = Column(String(20))
    ipk_tier = Column(String(20))
    nomor_hp = Column(String(20))
    email = Column(String(255))
    domisili = Column(String(100))
    last_position = Column(String(255))
    last_tenure = Column(String(50))
    last_company = Column(String(255))
    total_tenure = Column(String(50))
    pernah_di_fmcg = Column(String(3))
    sourcing_freelance = Column(String(3))
    tanggal_sourcing_freelance = Column(Date)
    sourcing_hr = Column(String(3))
    detail_keterangan_sourcing_hr = Column(Text)
    tanggal_sourcing = Column(Date)
    shortlist_cv = Column(String(3))
    detail_keterangan_shortlist_cv = Column(Text)
    tanggal_shortlist_cv = Column(Date)
    psikotes = Column(String(3))
    kode_psikotes = Column(String(50))
    detail_keterangan_psikotes = Column(Text)
    tanggal_psikotes = Column(Date)
    nilai_logika = Column(String(20))
    nilai_iq = Column(String(20))
    nilai_daya_tangkap = Column(String(20))
    nilai_ra = Column(String(20))
    disc = Column(String(20))
    hr_interview = Column(String(3))
    detail_keterangan_hr_interview = Column(Text)
    tanggal_hr_interview = Column(Date)
    technical_test_case_study = Column(String(3))
    detail_keterangan_technical_test = Column(Text)
    tanggal_technical_test = Column(Date)
    market_visit = Column(String(3))
    detail_market_visit = Column(Text)
    tanggal_market_visit = Column(Date)
    user_interview = Column(String(3))
    detail_keterangan_user_interview = Column(Text)
    tanggal_user_interview = Column(Date)
    panel_interview = Column(String(3))
    detail_keterangan_panel_interview = Column(Text)
    tanggal_panel_interview = Column(Date)
    reference_check = Column(String(3))
    detail_keterangan_reference_check = Column(Text)
    tanggal_reference_check = Column(Date)
    mcu = Column(String(3))
    detail_keterangan_mcu = Column(Text)
    tanggal_mcu = Column(Date)
    offering = Column(String(3))
    detail_keterangan_offering = Column(Text)
    tanggal_offering = Column(Date)
    notes = Column(Text)
    day1 = Column(String(3))
    detail_keterangan_day1 = Column(Text)
    tanggal_day1 = Column(Date)
    created_at = Column(TIMESTAMP, server_default=func.now())
    last_updated_at = Column(TIMESTAMP)
    last_compile_action = Column(String(20))
    source_file = Column(String(255))
    source_file_hash = Column(String(64))
    source_user_id = Column(Integer, ForeignKey("users.id"))
    source_cycle_id = Column(Integer, ForeignKey("upload_cycles.id"))

class MasterDropdown(Base):
    __tablename__ = "master_dropdown"
    id = Column(Integer, primary_key=True, index=True)
    kode_pic = Column(String(50))
    bu = Column(String(255))
    alasan = Column(Text)
    category_fptk = Column(String(50))
    pic_recruiter = Column(String(100), index=True)
    filter_fptk = Column(String(50))
    status = Column(String(20))
    lokasi_onboarding = Column(String(100))
    detail_sla = Column(Text)
    keterangan_0 = Column(Text)
    keterangan_1 = Column(Text)
    keterangan_cancel = Column(Text)
    nama_direktorat = Column(String(100))
    model = Column(String(20))
    sumber_sourcing = Column(String(50))
    jenjang_pendidikan = Column(String(20))
    nama_universitas_top10 = Column(String(255))
    jurusan = Column(String(100))
    university_tier = Column(String(20))
    ipk_tier = Column(String(20))
    keterangan_tidak_lolos_sourcing_1 = Column(Text)
    keterangan_tidak_lolos_sourcing_2 = Column(Text)
    keterangan_tidak_lolos_psikotes = Column(Text)
    keterangan_tidak_lolos_hr_interview = Column(Text)
    keterangan_tidak_lolos_user_panel = Column(Text)
    keterangan_tidak_lolos_technical_test = Column(Text)
    keterangan_tidak_lolos_market_visit = Column(Text)
    keterangan_tidak_lolos_reference_check = Column(Text)
    keterangan_tidak_menerima_offer = Column(Text)
    keterangan_tidak_lolos_mcu = Column(Text)
    keterangan_tidak_hadir_day1 = Column(Text)
    lokasi_pic_recruiter = Column(String(50))
    is_active = Column(Boolean, default=True)

class Blacklist(Base):
    __tablename__ = "blacklist"
    id = Column(Integer, primary_key=True, index=True)
    key_value = Column(String(255), unique=True, nullable=False)
    created_at = Column(TIMESTAMP, server_default=func.now())

class AuditLog(Base):
    __tablename__ = "audit_logs"
    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"))
    action = Column(String(50))
    table_name = Column(String(50))
    record_id = Column(Integer)
    old_value = Column(JSON)
    new_value = Column(JSON)
    ip_address = Column(String(45))
    user_agent = Column(Text)
    created_at = Column(TIMESTAMP, server_default=func.now())

class Evidence(Base):
    __tablename__ = "evidences"
    id = Column(Integer, primary_key=True, index=True)
    kode_unik = Column(String(50), index=True)
    posisi = Column(String(255))
    tanggal = Column(Date, index=True)
    file_name = Column(String(255))
    file_path = Column(String(500))
    file_size = Column(Integer)
    total_cv = Column(Integer, default=0)
    pic_recruiter = Column(String(100), index=True)
    user_id = Column(Integer, ForeignKey("users.id"))
    created_at = Column(TIMESTAMP, server_default=func.now())
    uploaded_at = Column(TIMESTAMP, server_default=func.now())
