# seed_master.py
from core.database import SessionLocal, init_db
from core.models import MasterDropdown

def seed_master_dropdown():
    db = SessionLocal()
    
    # Cek apakah sudah ada data
    count = db.query(MasterDropdown).count()
    if count > 0:
        print(f"✅ MasterDropdown sudah ada {count} data. Skip seeding.")
        db.close()
        return
    
    # Data dari file "Kode Dropdown" VBA
    master_data = [
        # Kode PIC | BU | Alasan | Category | PIC Recruiter | Filter | Status | Lokasi Onboarding | Detail SLA | Keterangan 0 | Keterangan 1 | Keterangan Cancel | Nama Direktorat | Model | Sumber Sourcing | Jenjang | Univ Top 10 | Jurusan | Univ Tier | IPK Tier
        {
            "kode_pic": "CORPPau",
            "bu": "PT CISARUA MOUNTAIN DAIRY, TBK",
            "alasan": "Karyawan Lama Keluar",
            "category_fptk": "NEW",
            "pic_recruiter": "Pauline",
            "filter_fptk": "CLAP FGDP",
            "status": "OP",
            "lokasi_onboarding": "HO Meruya",
            "detail_sla": "OP belum lewat SLA",
            "keterangan_0": "Area minim sumber daya",
            "keterangan_1": "Kandidat hasil referensi User",
            "keterangan_cancel": "Keterangan FPTK tidak sesuai kebutuhan",
            "nama_direktorat": "CEO Office",
            "model": "Model 1",
            "sumber_sourcing": "Jobstreet",
            "jenjang_pendidikan": "SMA/SMK",
            "nama_universitas_top10": "Universitas Indonesia",
            "jurusan": "IPA",
            "university_tier": "Top 3 PTN",
            "ipk_tier": "Lebih dari 3,5",
            "lokasi_pic_recruiter": "Corporate"
        },
        {
            "kode_pic": "CORPKar",
            "bu": "PT MACROSENTRA NIAGABOGA",
            "alasan": "Penambahan Personil",
            "category_fptk": "REPLACEMENT",
            "pic_recruiter": "Karin",
            "filter_fptk": "Level 1-2",
            "status": "Closed",
            "lokasi_onboarding": "Semarang",
            "detail_sla": "OP tidak lulus SLA",
            "keterangan_0": "User tidak responsif",
            "keterangan_1": "Talent pool besar",
            "keterangan_cancel": "FPTK diisi dengan karyawan mutasi/promosi",
            "nama_direktorat": "CEO, Corsec, & Investor Relation",
            "model": "Model 2",
            "sumber_sourcing": "LinkedIn",
            "jenjang_pendidikan": "D3",
            "nama_universitas_top10": "Universitas Gadjah Mada",
            "jurusan": "IPS",
            "university_tier": "Top 10 PTN",
            "ipk_tier": "Lebih dari 3,2",
            "lokasi_pic_recruiter": "CMD"
        },
        {
            "kode_pic": "CORPTih",
            "bu": "PT JAVA EGG SPECIALITIES",
            "alasan": "Jabatan Baru",
            "category_fptk": "",
            "pic_recruiter": "Ratih",
            "filter_fptk": "STO",
            "status": "Cancel",
            "lokasi_onboarding": "Cikupa",
            "detail_sla": "Closed lulus SLA",
            "keterangan_0": "Kandidat mengundurkan diri",
            "keterangan_1": "User responsif dalam proses seleksi",
            "keterangan_cancel": "Karyawan existing batal resign",
            "nama_direktorat": "Commercial CMD",
            "model": "Model 3",
            "sumber_sourcing": "Google Form",
            "jenjang_pendidikan": "D4",
            "nama_universitas_top10": "Institut Teknologi Bandung",
            "jurusan": "Administrasi Bisnis",
            "university_tier": "Top 20 PTN",
            "ipk_tier": "Kurang dari 3,5",
            "lokasi_pic_recruiter": "MS"
        },
        {
            "kode_pic": "CORPLex",
            "bu": "PT MACROPRIMA PANGANUTAMA",
            "alasan": "Karyawan Lama Mutasi",
            "category_fptk": "",
            "pic_recruiter": "Alexa",
            "filter_fptk": "Level 3",
            "status": "",
            "lokasi_onboarding": "Sentul",
            "detail_sla": "Closed tidak lulus SLA",
            "keterangan_0": "Kendala biaya/hasil Medical Check Up",
            "keterangan_1": "FPTK, urgent dan butuh cepat",
            "keterangan_cancel": "Melalui proses Internal Hiring",
            "nama_direktorat": "Commercial JES",
            "model": "Model 4",
            "sumber_sourcing": "Referensi User",
            "jenjang_pendidikan": "S1",
            "nama_universitas_top10": "Universitas Airlangga",
            "jurusan": "Administrasi Niaga",
            "university_tier": "Top 10 PTS",
            "ipk_tier": "Kurang dari 3,2",
            "lokasi_pic_recruiter": "JESS"
        },
        {
            "kode_pic": "CORPMar",
            "bu": "PT ARTHA RASA CIMORY",
            "alasan": "Karyawan Lama Promosi",
            "category_fptk": "",
            "pic_recruiter": "Marta",
            "filter_fptk": "Level 4",
            "status": "",
            "lokasi_onboarding": "Pasuruan",
            "detail_sla": "Cancel FPTK",
            "keterangan_0": "Kandidat, tidak sesuai preferensi user",
            "keterangan_1": "Kandidat tersedia dari talent pool existing",
            "keterangan_cancel": "Posisi di-hold oleh user",
            "nama_direktorat": "Commercial MP",
            "model": "",
            "sumber_sourcing": "Referensi Karyawan",
            "jenjang_pendidikan": "S2",
            "nama_universitas_top10": "Universitas Padjadjaran",
            "jurusan": "Administrasi Publik",
            "university_tier": "Lainnya",
            "ipk_tier": "",
            "lokasi_pic_recruiter": "MP"
        },
        {
            "kode_pic": "CORPBrit",
            "bu": "PT MACROTAMA BINASANTIKA",
            "alasan": "",
            "category_fptk": "",
            "pic_recruiter": "Brittney",
            "filter_fptk": "",
            "status": "",
            "lokasi_onboarding": "Area Sales",
            "detail_sla": "",
            "keterangan_0": "User mengubah kualifikasi kandidat",
            "keterangan_1": "Kandidat hasil referensi karyawan",
            "keterangan_cancel": "Karyawan existing batal resign",
            "nama_direktorat": "Finance & Business Support",
            "model": "",
            "sumber_sourcing": "Campus Hiring",
            "jenjang_pendidikan": "",
            "nama_universitas_top10": "Universitas Diponegoro",
            "jurusan": "Agribisnis",
            "university_tier": "",
            "ipk_tier": "",
            "lokasi_pic_recruiter": ""
        },
        {
            "kode_pic": "CORPOme",
            "bu": "",
            "alasan": "",
            "category_fptk": "",
            "pic_recruiter": "Omega",
            "filter_fptk": "",
            "status": "",
            "lokasi_onboarding": "",
            "detail_sla": "",
            "keterangan_0": "Kandidat meminta penyesuaian kompensasi di luar budget",
            "keterangan_1": "Kualifikasi posisi mudah ditemukan di market",
            "keterangan_cancel": "Perubahan struktur organisasi",
            "nama_direktorat": "Logistic & Distribution",
            "model": "",
            "sumber_sourcing": "",
            "jenjang_pendidikan": "",
            "nama_universitas_top10": "Universitas Brawijaya",
            "jurusan": "Agroteknologi",
            "university_tier": "",
            "ipk_tier": "",
            "lokasi_pic_recruiter": ""
        },
        {
            "kode_pic": "CORPZwei",
            "bu": "",
            "alasan": "",
            "category_fptk": "",
            "pic_recruiter": "Zwei",
            "filter_fptk": "",
            "status": "",
            "lokasi_onboarding": "",
            "detail_sla": "",
            "keterangan_0": "Posisi sempat di-hold sementara oleh user",
            "keterangan_1": "",
            "keterangan_cancel": "FPTK dibuat duplikat",
            "nama_direktorat": "Manufacture CMD",
            "model": "",
            "sumber_sourcing": "",
            "jenjang_pendidikan": "",
            "nama_universitas_top10": "Institut Pertanian Bogor",
            "jurusan": "Akuntansi",
            "university_tier": "",
            "ipk_tier": "",
            "lokasi_pic_recruiter": ""
        },
        {
            "kode_pic": "CORPKen",
            "bu": "",
            "alasan": "",
            "category_fptk": "",
            "pic_recruiter": "Kenthansen",
            "filter_fptk": "",
            "status": "",
            "lokasi_onboarding": "",
            "detail_sla": "",
            "keterangan_0": "Kendala administrasi atau dokumen kandidat",
            "keterangan_1": "",
            "keterangan_cancel": "",
            "nama_direktorat": "Manufacture JES",
            "model": "",
            "sumber_sourcing": "",
            "jenjang_pendidikan": "",
            "nama_universitas_top10": "Universitas Sebelas Maret",
            "jurusan": "Analisis Kimia",
            "university_tier": "",
            "ipk_tier": "",
            "lokasi_pic_recruiter": ""
        },
        {
            "kode_pic": "CORPDesi",
            "bu": "",
            "alasan": "",
            "category_fptk": "",
            "pic_recruiter": "Desi",
            "filter_fptk": "",
            "status": "",
            "lokasi_onboarding": "",
            "detail_sla": "",
            "keterangan_0": "Kendala medical check-up",
            "keterangan_1": "",
            "keterangan_cancel": "",
            "nama_direktorat": "Manufacture MP",
            "model": "",
            "sumber_sourcing": "",
            "jenjang_pendidikan": "",
            "nama_universitas_top10": "Telkom University",
            "jurusan": "Analitik Bisnis",
            "university_tier": "",
            "ipk_tier": "",
            "lokasi_pic_recruiter": ""
        },
        {
            "kode_pic": "CMDEls",
            "bu": "",
            "alasan": "",
            "category_fptk": "",
            "pic_recruiter": "Elsi",
            "filter_fptk": "",
            "status": "",
            "lokasi_onboarding": "",
            "detail_sla": "",
            "keterangan_0": "Hari libur/cuti bersama memengaruhi proses",
            "keterangan_1": "",
            "keterangan_cancel": "",
            "nama_direktorat": "Procurement CMD & Corporate",
            "model": "",
            "sumber_sourcing": "",
            "jenjang_pendidikan": "",
            "nama_universitas_top10": "Lainnya",
            "jurusan": "Aktuaria",
            "university_tier": "",
            "ipk_tier": "",
            "lokasi_pic_recruiter": ""
        },
        {
            "kode_pic": "CMDSal",
            "bu": "",
            "alasan": "",
            "category_fptk": "",
            "pic_recruiter": "Salwa",
            "filter_fptk": "",
            "status": "",
            "lokasi_onboarding": "",
            "detail_sla": "",
            "keterangan_0": "",
            "keterangan_1": "",
            "keterangan_cancel": "",
            "nama_direktorat": "Procurement MP & JES",
            "model": "",
            "sumber_sourcing": "",
            "jenjang_pendidikan": "SMA/SMK",
            "nama_universitas_top10": "",
            "jurusan": "Arsitektur",
            "university_tier": "",
            "ipk_tier": "",
            "lokasi_pic_recruiter": ""
        },
        {
            "kode_pic": "CMDWah",
            "bu": "",
            "alasan": "",
            "category_fptk": "",
            "pic_recruiter": "Wahyu",
            "filter_fptk": "",
            "status": "",
            "lokasi_onboarding": "",
            "detail_sla": "",
            "keterangan_0": "",
            "keterangan_1": "",
            "keterangan_cancel": "",
            "nama_direktorat": "Sales General Trade CMD",
            "model": "",
            "sumber_sourcing": "",
            "jenjang_pendidikan": "",
            "nama_universitas_top10": "",
            "jurusan": "Asuransi",
            "university_tier": "",
            "ipk_tier": "",
            "lokasi_pic_recruiter": ""
        },
        {
            "kode_pic": "MPAch",
            "bu": "",
            "alasan": "",
            "category_fptk": "",
            "pic_recruiter": "Achmad",
            "filter_fptk": "",
            "status": "",
            "lokasi_onboarding": "",
            "detail_sla": "",
            "keterangan_0": "",
            "keterangan_1": "",
            "keterangan_cancel": "",
            "nama_direktorat": "Sales General Trade JES",
            "model": "",
            "sumber_sourcing": "",
            "jenjang_pendidikan": "",
            "nama_universitas_top10": "",
            "jurusan": "Bioinformatika",
            "university_tier": "",
            "ipk_tier": "",
            "lokasi_pic_recruiter": ""
        },
        {
            "kode_pic": "MPKas",
            "bu": "",
            "alasan": "",
            "category_fptk": "",
            "pic_recruiter": "Kasanah",
            "filter_fptk": "",
            "status": "",
            "lokasi_onboarding": "",
            "detail_sla": "",
            "keterangan_0": "",
            "keterangan_1": "",
            "keterangan_cancel": "",
            "nama_direktorat": "Sales General Trade MP",
            "model": "",
            "sumber_sourcing": "",
            "jenjang_pendidikan": "",
            "nama_universitas_top10": "",
            "jurusan": "Biologi",
            "university_tier": "",
            "ipk_tier": "",
            "lokasi_pic_recruiter": ""
        },
        {
            "kode_pic": "MPEli",
            "bu": "",
            "alasan": "",
            "category_fptk": "",
            "pic_recruiter": "Eli",
            "filter_fptk": "",
            "status": "",
            "lokasi_onboarding": "",
            "detail_sla": "",
            "keterangan_0": "",
            "keterangan_1": "",
            "keterangan_cancel": "",
            "nama_direktorat": "Sales International Market",
            "model": "",
            "sumber_sourcing": "",
            "jenjang_pendidikan": "",
            "nama_universitas_top10": "",
            "jurusan": "Bioteknologi",
            "university_tier": "",
            "ipk_tier": "",
            "lokasi_pic_recruiter": ""
        },
        {
            "kode_pic": "MPGab",
            "bu": "",
            "alasan": "",
            "category_fptk": "",
            "pic_recruiter": "Gabbie",
            "filter_fptk": "",
            "status": "",
            "lokasi_onboarding": "",
            "detail_sla": "",
            "keterangan_0": "",
            "keterangan_1": "",
            "keterangan_cancel": "",
            "nama_direktorat": "Sales Modern Trade",
            "model": "",
            "sumber_sourcing": "",
            "jenjang_pendidikan": "",
            "nama_universitas_top10": "",
            "jurusan": "Bisnis dan Manajemen",
            "university_tier": "",
            "ipk_tier": "",
            "lokasi_pic_recruiter": ""
        },
        {
            "kode_pic": "MSLeo",
            "bu": "",
            "alasan": "",
            "category_fptk": "",
            "pic_recruiter": "Leo",
            "filter_fptk": "",
            "status": "",
            "lokasi_onboarding": "",
            "detail_sla": "",
            "keterangan_0": "",
            "keterangan_1": "",
            "keterangan_cancel": "",
            "nama_direktorat": "",
            "model": "",
            "sumber_sourcing": "",
            "jenjang_pendidikan": "",
            "nama_universitas_top10": "",
            "jurusan": "Bisnis Digital",
            "university_tier": "",
            "ipk_tier": "",
            "lokasi_pic_recruiter": ""
        },
        {
            "kode_pic": "JESSFis",
            "bu": "",
            "alasan": "",
            "category_fptk": "",
            "pic_recruiter": "Fiscall",
            "filter_fptk": "",
            "status": "",
            "lokasi_onboarding": "",
            "detail_sla": "",
            "keterangan_0": "",
            "keterangan_1": "",
            "keterangan_cancel": "",
            "nama_direktorat": "",
            "model": "",
            "sumber_sourcing": "",
            "jenjang_pendidikan": "",
            "nama_universitas_top10": "",
            "jurusan": "Bisnis Internasional",
            "university_tier": "",
            "ipk_tier": "",
            "lokasi_pic_recruiter": ""
        },
        # Tambahkan jurusan lainnya
        *[{"kode_pic": "", "bu": "", "alasan": "", "category_fptk": "", "pic_recruiter": "", "filter_fptk": "", "status": "", "lokasi_onboarding": "", "detail_sla": "", "keterangan_0": "", "keterangan_1": "", "keterangan_cancel": "", "nama_direktorat": "", "model": "", "sumber_sourcing": "", "jenjang_pendidikan": "", "nama_universitas_top10": "", "jurusan": j, "university_tier": "", "ipk_tier": "", "lokasi_pic_recruiter": ""} 
         for j in ["Bisnis Syariah", "Budidaya Perairan", "Ekonomi Bisnis", "Ekonomi Islam", "Ekonomi Pembangunan", "Ekonomi Syariah", "Farmasi", "Fisika", "Geofisika", "Hubungan Internasional", "Hubungan Masyarakat", "Ilmu Administrasi Negara", "Ilmu Ekonomi", "Ilmu Gizi", "Ilmu Kelautan", "Ilmu Komputer", "Ilmu Tanah", "Instrumentasi", "Keamanan Siber", "Kedokteran Hewan", "Kehutanan", "Kesehatan Masyarakat", "Keuangan", "Kimia", "Kewirausahaan", "Logistik Bisnis", "Mekatronika", "Manajemen", "Manajemen Acara", "Manajemen Agribisnis", "Manajemen Bisnis", "Manajemen Industri", "Manajemen Informatika Bisnis", "Manajemen Keuangan", "Manajemen Logistik", "Manajemen Operasi", "Manajemen Pemasaran", "Manajemen Perhotelan", "Manajemen Perkantoran", "Manajemen Proyek", "Manajemen Rantai Pasok", "Manajemen Risiko", "Manajemen Ritel", "Manajemen Sumber Daya Manusia", "Manajemen Transportasi", "Matematika", "Meteorologi", "Oseanografi", "Pariwisata", "Pemasaran", "Pemasaran Digital", "Perbankan", "Perdagangan Elektronik", "Perdagangan Internasional", "Perencanaan Wilayah dan Kota", "Perhotelan", "Perikanan", "Perpajakan", "Peternakan", "Proteksi Tanaman", "Robotika dan Kecerdasan Buatan", "Sains Data", "Sekretari", "Sistem Informasi", "Statistika", "Teknik Biomedis", "Teknik Dirgantara", "Teknik Elektro", "Teknik Fisika", "Teknik Geodesi", "Teknik Geologi", "Teknik Industri", "Teknik Informatika", "Teknik Kelautan", "Teknik Kimia", "Teknik Lingkungan", "Teknik Material", "Teknik Mesin", "Teknik Metalurgi", "Teknik Nuklir", "Teknik Otomotif", "Teknik Pangan", "Teknik Perkapalan", "Teknik Perminyakan", "Teknik Sipil", "Teknik Telekomunikasi", "Teknologi Finansial", "Teknologi Hasil Pertanian", "Teknologi Hasil Peternakan", "Teknologi Industri Pertanian", "Teknologi Rekayasa Elektronika", "Teknologi Rekayasa Energi Terbarukan", "Teknologi Rekayasa Manufaktur", "Teknologi Rekayasa Otomotif", "Teknologi Rekayasa Perangkat Lunak", "Lainnya"]
    ]
    
    for data in master_data:
        record = MasterDropdown(**data)
        db.add(record)
    
    db.commit()
    print(f"✅ {len(master_data)} data MasterDropdown berhasil disimpan!")
    db.close()

if __name__ == "__main__":
    init_db()
    seed_master_dropdown()
